/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class AlleleMatrixDetails implements Serializable {
  
  @SerializedName("description")
  private String description = null;
  @SerializedName("lastUpdated")
  private Date lastUpdated = null;
  @SerializedName("matrixDbId")
  private String matrixDbId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("studyDbId")
  private String studyDbId = null;

  /**
   * How the matrix was generated
   **/
  @ApiModelProperty(value = "How the matrix was generated")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * A date format
   **/
  @ApiModelProperty(value = "A date format")
  public Date getLastUpdated() {
    return lastUpdated;
  }
  public void setLastUpdated(Date lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  /**
   * ID of the matrix
   **/
  @ApiModelProperty(value = "ID of the matrix")
  public String getMatrixDbId() {
    return matrixDbId;
  }
  public void setMatrixDbId(String matrixDbId) {
    this.matrixDbId = matrixDbId;
  }

  /**
   * Name of the matrix
   **/
  @ApiModelProperty(value = "Name of the matrix")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Link to the study where the matrix was produced
   **/
  @ApiModelProperty(value = "Link to the study where the matrix was produced")
  public String getStudyDbId() {
    return studyDbId;
  }
  public void setStudyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlleleMatrixDetails alleleMatrixDetails = (AlleleMatrixDetails) o;
    return (this.description == null ? alleleMatrixDetails.description == null : this.description.equals(alleleMatrixDetails.description)) &&
        (this.lastUpdated == null ? alleleMatrixDetails.lastUpdated == null : this.lastUpdated.equals(alleleMatrixDetails.lastUpdated)) &&
        (this.matrixDbId == null ? alleleMatrixDetails.matrixDbId == null : this.matrixDbId.equals(alleleMatrixDetails.matrixDbId)) &&
        (this.name == null ? alleleMatrixDetails.name == null : this.name.equals(alleleMatrixDetails.name)) &&
        (this.studyDbId == null ? alleleMatrixDetails.studyDbId == null : this.studyDbId.equals(alleleMatrixDetails.studyDbId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.lastUpdated == null ? 0: this.lastUpdated.hashCode());
    result = 31 * result + (this.matrixDbId == null ? 0: this.matrixDbId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.studyDbId == null ? 0: this.studyDbId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlleleMatrixDetails {\n");
    
    sb.append("  description: ").append(description).append("\n");
    sb.append("  lastUpdated: ").append(lastUpdated).append("\n");
    sb.append("  matrixDbId: ").append(matrixDbId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  studyDbId: ").append(studyDbId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
