/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class AlleleMatrixSearchRequest implements Serializable {
  
  @SerializedName("expandHomozygotes")
  private Boolean expandHomozygotes = null;
  @SerializedName("format")
  private String format = null;
  @SerializedName("markerDbId")
  private List<String> markerDbId = null;
  @SerializedName("markerprofileDbId")
  private List<String> markerprofileDbId = null;
  @SerializedName("matrixDbId")
  private List<String> matrixDbId = null;
  @SerializedName("page")
  private Integer page = null;
  @SerializedName("pageSize")
  private Integer pageSize = null;
  @SerializedName("sepPhased")
  private String sepPhased = null;
  @SerializedName("sepUnphased")
  private String sepUnphased = null;
  @SerializedName("unknownString")
  private String unknownString = null;

  /**
   * Should homozygotes be expanded (true) or collapsed into a single occurence (false)
   **/
  @ApiModelProperty(value = "Should homozygotes be expanded (true) or collapsed into a single occurence (false)")
  public Boolean getExpandHomozygotes() {
    return expandHomozygotes;
  }
  public void setExpandHomozygotes(Boolean expandHomozygotes) {
    this.expandHomozygotes = expandHomozygotes;
  }

  /**
   * The data format of the response data. ie \"json\", \"tsv\", etc
   **/
  @ApiModelProperty(value = "The data format of the response data. ie \"json\", \"tsv\", etc")
  public String getFormat() {
    return format;
  }
  public void setFormat(String format) {
    this.format = format;
  }

  /**
   * An ID which uniquely identifies a Marker
   **/
  @ApiModelProperty(value = "An ID which uniquely identifies a Marker")
  public List<String> getMarkerDbId() {
    return markerDbId;
  }
  public void setMarkerDbId(List<String> markerDbId) {
    this.markerDbId = markerDbId;
  }

  /**
   * An ID which uniquely identifies a Marker Profile
   **/
  @ApiModelProperty(value = "An ID which uniquely identifies a Marker Profile")
  public List<String> getMarkerprofileDbId() {
    return markerprofileDbId;
  }
  public void setMarkerprofileDbId(List<String> markerprofileDbId) {
    this.markerprofileDbId = markerprofileDbId;
  }

  /**
   * An ID which uniquely identifies an Allele Matrix
   **/
  @ApiModelProperty(value = "An ID which uniquely identifies an Allele Matrix")
  public List<String> getMatrixDbId() {
    return matrixDbId;
  }
  public void setMatrixDbId(List<String> matrixDbId) {
    this.matrixDbId = matrixDbId;
  }

  /**
   * Which page of the \"data\" array to return. The page indexing starts at 0 (page=0 will return the first page). Default is 0.
   **/
  @ApiModelProperty(value = "Which page of the \"data\" array to return. The page indexing starts at 0 (page=0 will return the first page). Default is 0.")
  public Integer getPage() {
    return page;
  }
  public void setPage(Integer page) {
    this.page = page;
  }

  /**
   * The maximum number of items to return per page of the \"data\" array. Default is 1000.
   **/
  @ApiModelProperty(value = "The maximum number of items to return per page of the \"data\" array. Default is 1000.")
  public Integer getPageSize() {
    return pageSize;
  }
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  /**
   * The string to use as a separator for phased allele calls.
   **/
  @ApiModelProperty(value = "The string to use as a separator for phased allele calls.")
  public String getSepPhased() {
    return sepPhased;
  }
  public void setSepPhased(String sepPhased) {
    this.sepPhased = sepPhased;
  }

  /**
   * The string to use as a separator for unphased allele calls.
   **/
  @ApiModelProperty(value = "The string to use as a separator for unphased allele calls.")
  public String getSepUnphased() {
    return sepUnphased;
  }
  public void setSepUnphased(String sepUnphased) {
    this.sepUnphased = sepUnphased;
  }

  /**
   * The string to use as a representation for missing data.
   **/
  @ApiModelProperty(value = "The string to use as a representation for missing data.")
  public String getUnknownString() {
    return unknownString;
  }
  public void setUnknownString(String unknownString) {
    this.unknownString = unknownString;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlleleMatrixSearchRequest alleleMatrixSearchRequest = (AlleleMatrixSearchRequest) o;
    return (this.expandHomozygotes == null ? alleleMatrixSearchRequest.expandHomozygotes == null : this.expandHomozygotes.equals(alleleMatrixSearchRequest.expandHomozygotes)) &&
        (this.format == null ? alleleMatrixSearchRequest.format == null : this.format.equals(alleleMatrixSearchRequest.format)) &&
        (this.markerDbId == null ? alleleMatrixSearchRequest.markerDbId == null : this.markerDbId.equals(alleleMatrixSearchRequest.markerDbId)) &&
        (this.markerprofileDbId == null ? alleleMatrixSearchRequest.markerprofileDbId == null : this.markerprofileDbId.equals(alleleMatrixSearchRequest.markerprofileDbId)) &&
        (this.matrixDbId == null ? alleleMatrixSearchRequest.matrixDbId == null : this.matrixDbId.equals(alleleMatrixSearchRequest.matrixDbId)) &&
        (this.page == null ? alleleMatrixSearchRequest.page == null : this.page.equals(alleleMatrixSearchRequest.page)) &&
        (this.pageSize == null ? alleleMatrixSearchRequest.pageSize == null : this.pageSize.equals(alleleMatrixSearchRequest.pageSize)) &&
        (this.sepPhased == null ? alleleMatrixSearchRequest.sepPhased == null : this.sepPhased.equals(alleleMatrixSearchRequest.sepPhased)) &&
        (this.sepUnphased == null ? alleleMatrixSearchRequest.sepUnphased == null : this.sepUnphased.equals(alleleMatrixSearchRequest.sepUnphased)) &&
        (this.unknownString == null ? alleleMatrixSearchRequest.unknownString == null : this.unknownString.equals(alleleMatrixSearchRequest.unknownString));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.expandHomozygotes == null ? 0: this.expandHomozygotes.hashCode());
    result = 31 * result + (this.format == null ? 0: this.format.hashCode());
    result = 31 * result + (this.markerDbId == null ? 0: this.markerDbId.hashCode());
    result = 31 * result + (this.markerprofileDbId == null ? 0: this.markerprofileDbId.hashCode());
    result = 31 * result + (this.matrixDbId == null ? 0: this.matrixDbId.hashCode());
    result = 31 * result + (this.page == null ? 0: this.page.hashCode());
    result = 31 * result + (this.pageSize == null ? 0: this.pageSize.hashCode());
    result = 31 * result + (this.sepPhased == null ? 0: this.sepPhased.hashCode());
    result = 31 * result + (this.sepUnphased == null ? 0: this.sepUnphased.hashCode());
    result = 31 * result + (this.unknownString == null ? 0: this.unknownString.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlleleMatrixSearchRequest {\n");
    
    sb.append("  expandHomozygotes: ").append(expandHomozygotes).append("\n");
    sb.append("  format: ").append(format).append("\n");
    sb.append("  markerDbId: ").append(markerDbId).append("\n");
    sb.append("  markerprofileDbId: ").append(markerprofileDbId).append("\n");
    sb.append("  matrixDbId: ").append(matrixDbId).append("\n");
    sb.append("  page: ").append(page).append("\n");
    sb.append("  pageSize: ").append(pageSize).append("\n");
    sb.append("  sepPhased: ").append(sepPhased).append("\n");
    sb.append("  sepUnphased: ").append(sepUnphased).append("\n");
    sb.append("  unknownString: ").append(unknownString).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
