/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class MarkerSummaryMap implements Serializable {
  
  @SerializedName("linkageGroupName")
  private String linkageGroupName = null;
  @SerializedName("location")
  private String location = null;
  @SerializedName("markerDbId")
  private String markerDbId = null;
  @SerializedName("markerName")
  private String markerName = null;

  /**
   * The Uniquely Identifiable name of this linkage group
   **/
  @ApiModelProperty(value = "The Uniquely Identifiable name of this linkage group")
  public String getLinkageGroupName() {
    return linkageGroupName;
  }
  public void setLinkageGroupName(String linkageGroupName) {
    this.linkageGroupName = linkageGroupName;
  }

  /**
   * The position of a marker within a linkage group
   **/
  @ApiModelProperty(value = "The position of a marker within a linkage group")
  public String getLocation() {
    return location;
  }
  public void setLocation(String location) {
    this.location = location;
  }

  /**
   * Internal db identifier
   **/
  @ApiModelProperty(value = "Internal db identifier")
  public String getMarkerDbId() {
    return markerDbId;
  }
  public void setMarkerDbId(String markerDbId) {
    this.markerDbId = markerDbId;
  }

  /**
   * The human readable name for a marker
   **/
  @ApiModelProperty(value = "The human readable name for a marker")
  public String getMarkerName() {
    return markerName;
  }
  public void setMarkerName(String markerName) {
    this.markerName = markerName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarkerSummaryMap markerSummaryMap = (MarkerSummaryMap) o;
    return (this.linkageGroupName == null ? markerSummaryMap.linkageGroupName == null : this.linkageGroupName.equals(markerSummaryMap.linkageGroupName)) &&
        (this.location == null ? markerSummaryMap.location == null : this.location.equals(markerSummaryMap.location)) &&
        (this.markerDbId == null ? markerSummaryMap.markerDbId == null : this.markerDbId.equals(markerSummaryMap.markerDbId)) &&
        (this.markerName == null ? markerSummaryMap.markerName == null : this.markerName.equals(markerSummaryMap.markerName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.linkageGroupName == null ? 0: this.linkageGroupName.hashCode());
    result = 31 * result + (this.location == null ? 0: this.location.hashCode());
    result = 31 * result + (this.markerDbId == null ? 0: this.markerDbId.hashCode());
    result = 31 * result + (this.markerName == null ? 0: this.markerName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarkerSummaryMap {\n");
    
    sb.append("  linkageGroupName: ").append(linkageGroupName).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  markerDbId: ").append(markerDbId).append("\n");
    sb.append("  markerName: ").append(markerName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
