/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

/**
 * Method metadata
 **/
@ApiModel(description = "Method metadata")
public class Method implements Serializable {
  
  @SerializedName("class")
  private String _class = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("formula")
  private String formula = null;
  @SerializedName("methodDbId")
  private String methodDbId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("reference")
  private String reference = null;

  /**
   * Method class (examples: \"Measurement\", \"Counting\", \"Estimation\", \"Computation\", etc.
   **/
  @ApiModelProperty(value = "Method class (examples: \"Measurement\", \"Counting\", \"Estimation\", \"Computation\", etc.")
  public String getMethodClass() {
    return _class;
  }
  public void setClass(String _class) {
    this._class = _class;
  }

  /**
   * Method description.
   **/
  @ApiModelProperty(value = "Method description.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * For computational methods i.e., when the method consists in assessing the trait by computing measurements, write the generic formula used for the calculation
   **/
  @ApiModelProperty(value = "For computational methods i.e., when the method consists in assessing the trait by computing measurements, write the generic formula used for the calculation")
  public String getFormula() {
    return formula;
  }
  public void setFormula(String formula) {
    this.formula = formula;
  }

  /**
   * Method unique identifier
   **/
  @ApiModelProperty(value = "Method unique identifier")
  public String getMethodDbId() {
    return methodDbId;
  }
  public void setMethodDbId(String methodDbId) {
    this.methodDbId = methodDbId;
  }

  /**
   * Method name (usually a short name)
   **/
  @ApiModelProperty(value = "Method name (usually a short name)")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Bibliographical reference describing the method.
   **/
  @ApiModelProperty(value = "Bibliographical reference describing the method.")
  public String getReference() {
    return reference;
  }
  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Method method = (Method) o;
    return (this._class == null ? method._class == null : this._class.equals(method._class)) &&
        (this.description == null ? method.description == null : this.description.equals(method.description)) &&
        (this.formula == null ? method.formula == null : this.formula.equals(method.formula)) &&
        (this.methodDbId == null ? method.methodDbId == null : this.methodDbId.equals(method.methodDbId)) &&
        (this.name == null ? method.name == null : this.name.equals(method.name)) &&
        (this.reference == null ? method.reference == null : this.reference.equals(method.reference));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this._class == null ? 0: this._class.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.formula == null ? 0: this.formula.hashCode());
    result = 31 * result + (this.methodDbId == null ? 0: this.methodDbId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.reference == null ? 0: this.reference.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Method {\n");
    
    sb.append("  _class: ").append(_class).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  formula: ").append(formula).append("\n");
    sb.append("  methodDbId: ").append(methodDbId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  reference: ").append(reference).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
