/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class ObservationUnitPosition implements Serializable {
  
  @SerializedName("X")
  private String X = null;
  @SerializedName("Y")
  private String Y = null;
  @SerializedName("additionalInfo")
  private Map<String, String> additionalInfo = null;
  @SerializedName("blockNumber")
  private String blockNumber = null;
  public enum EntryTypeEnum {
     CHECK,  TEST,  FILLER, 
  };
  @SerializedName("entryType")
  private EntryTypeEnum entryType = null;
  @SerializedName("germplasmDbId")
  private String germplasmDbId = null;
  @SerializedName("germplasmName")
  private String germplasmName = null;
  @SerializedName("observationLevel")
  private String observationLevel = null;
  @SerializedName("observationUnitDbId")
  private String observationUnitDbId = null;
  @SerializedName("observationUnitName")
  private String observationUnitName = null;
  @SerializedName("replicate")
  private String replicate = null;
  @SerializedName("studyDbId")
  private String studyDbId = null;

  /**
   * The X position coordinate for an observation unit. Different systems may use different coordinate systems.
   **/
  @ApiModelProperty(value = "The X position coordinate for an observation unit. Different systems may use different coordinate systems.")
  public String getX() {
    return X;
  }
  public void setX(String X) {
    this.X = X;
  }

  /**
   * The Y position coordinate for an observation unit. Different systems may use different coordinate systems.
   **/
  @ApiModelProperty(value = "The Y position coordinate for an observation unit. Different systems may use different coordinate systems.")
  public String getY() {
    return Y;
  }
  public void setY(String Y) {
    this.Y = Y;
  }

  /**
   * Additional arbitrary info
   **/
  @ApiModelProperty(value = "Additional arbitrary info")
  public Map<String, String> getAdditionalInfo() {
    return additionalInfo;
  }
  public void setAdditionalInfo(Map<String, String> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  /**
   * The block number for an observation unit. Different systems may use different block designs.
   **/
  @ApiModelProperty(value = "The block number for an observation unit. Different systems may use different block designs.")
  public String getBlockNumber() {
    return blockNumber;
  }
  public void setBlockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
  }

  /**
   * The type of entry for this observation unit. ex. \"check\", \"test\", \"filler\"
   **/
  @ApiModelProperty(value = "The type of entry for this observation unit. ex. \"check\", \"test\", \"filler\"")
  public EntryTypeEnum getEntryType() {
    return entryType;
  }
  public void setEntryType(EntryTypeEnum entryType) {
    this.entryType = entryType;
  }

  /**
   *  The ID which uniquely identifies a germplasm
   **/
  @ApiModelProperty(value = " The ID which uniquely identifies a germplasm")
  public String getGermplasmDbId() {
    return germplasmDbId;
  }
  public void setGermplasmDbId(String germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
  }

  /**
   * Name of the germplasm. It can be the prefered name and does not have to be unique.
   **/
  @ApiModelProperty(value = "Name of the germplasm. It can be the prefered name and does not have to be unique.")
  public String getGermplasmName() {
    return germplasmName;
  }
  public void setGermplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
  }

  /**
   * The level of an observation unit. ex. \"plot\", \"plant\"
   **/
  @ApiModelProperty(value = "The level of an observation unit. ex. \"plot\", \"plant\"")
  public String getObservationLevel() {
    return observationLevel;
  }
  public void setObservationLevel(String observationLevel) {
    this.observationLevel = observationLevel;
  }

  /**
   * The ID which uniquely identifies an observation unit
   **/
  @ApiModelProperty(value = "The ID which uniquely identifies an observation unit")
  public String getObservationUnitDbId() {
    return observationUnitDbId;
  }
  public void setObservationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
  }

  /**
   * A human readable name for an observation unit
   **/
  @ApiModelProperty(value = "A human readable name for an observation unit")
  public String getObservationUnitName() {
    return observationUnitName;
  }
  public void setObservationUnitName(String observationUnitName) {
    this.observationUnitName = observationUnitName;
  }

  /**
   * The replicate number of an observation unit. May be the same as blockNumber.
   **/
  @ApiModelProperty(value = "The replicate number of an observation unit. May be the same as blockNumber.")
  public String getReplicate() {
    return replicate;
  }
  public void setReplicate(String replicate) {
    this.replicate = replicate;
  }

  /**
   * The ID which uniquely identifies a study within the given database server
   **/
  @ApiModelProperty(value = "The ID which uniquely identifies a study within the given database server")
  public String getStudyDbId() {
    return studyDbId;
  }
  public void setStudyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObservationUnitPosition observationUnitPosition = (ObservationUnitPosition) o;
    return (this.X == null ? observationUnitPosition.X == null : this.X.equals(observationUnitPosition.X)) &&
        (this.Y == null ? observationUnitPosition.Y == null : this.Y.equals(observationUnitPosition.Y)) &&
        (this.additionalInfo == null ? observationUnitPosition.additionalInfo == null : this.additionalInfo.equals(observationUnitPosition.additionalInfo)) &&
        (this.blockNumber == null ? observationUnitPosition.blockNumber == null : this.blockNumber.equals(observationUnitPosition.blockNumber)) &&
        (this.entryType == null ? observationUnitPosition.entryType == null : this.entryType.equals(observationUnitPosition.entryType)) &&
        (this.germplasmDbId == null ? observationUnitPosition.germplasmDbId == null : this.germplasmDbId.equals(observationUnitPosition.germplasmDbId)) &&
        (this.germplasmName == null ? observationUnitPosition.germplasmName == null : this.germplasmName.equals(observationUnitPosition.germplasmName)) &&
        (this.observationLevel == null ? observationUnitPosition.observationLevel == null : this.observationLevel.equals(observationUnitPosition.observationLevel)) &&
        (this.observationUnitDbId == null ? observationUnitPosition.observationUnitDbId == null : this.observationUnitDbId.equals(observationUnitPosition.observationUnitDbId)) &&
        (this.observationUnitName == null ? observationUnitPosition.observationUnitName == null : this.observationUnitName.equals(observationUnitPosition.observationUnitName)) &&
        (this.replicate == null ? observationUnitPosition.replicate == null : this.replicate.equals(observationUnitPosition.replicate)) &&
        (this.studyDbId == null ? observationUnitPosition.studyDbId == null : this.studyDbId.equals(observationUnitPosition.studyDbId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.X == null ? 0: this.X.hashCode());
    result = 31 * result + (this.Y == null ? 0: this.Y.hashCode());
    result = 31 * result + (this.additionalInfo == null ? 0: this.additionalInfo.hashCode());
    result = 31 * result + (this.blockNumber == null ? 0: this.blockNumber.hashCode());
    result = 31 * result + (this.entryType == null ? 0: this.entryType.hashCode());
    result = 31 * result + (this.germplasmDbId == null ? 0: this.germplasmDbId.hashCode());
    result = 31 * result + (this.germplasmName == null ? 0: this.germplasmName.hashCode());
    result = 31 * result + (this.observationLevel == null ? 0: this.observationLevel.hashCode());
    result = 31 * result + (this.observationUnitDbId == null ? 0: this.observationUnitDbId.hashCode());
    result = 31 * result + (this.observationUnitName == null ? 0: this.observationUnitName.hashCode());
    result = 31 * result + (this.replicate == null ? 0: this.replicate.hashCode());
    result = 31 * result + (this.studyDbId == null ? 0: this.studyDbId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObservationUnitPosition {\n");
    
    sb.append("  X: ").append(X).append("\n");
    sb.append("  Y: ").append(Y).append("\n");
    sb.append("  additionalInfo: ").append(additionalInfo).append("\n");
    sb.append("  blockNumber: ").append(blockNumber).append("\n");
    sb.append("  entryType: ").append(entryType).append("\n");
    sb.append("  germplasmDbId: ").append(germplasmDbId).append("\n");
    sb.append("  germplasmName: ").append(germplasmName).append("\n");
    sb.append("  observationLevel: ").append(observationLevel).append("\n");
    sb.append("  observationUnitDbId: ").append(observationUnitDbId).append("\n");
    sb.append("  observationUnitName: ").append(observationUnitName).append("\n");
    sb.append("  replicate: ").append(replicate).append("\n");
    sb.append("  studyDbId: ").append(studyDbId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
