/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ObservationSummary;
import io.swagger.client.model.ObservationUnitXref;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class ObservationUnitStudy implements Serializable {
  
  @SerializedName("X")
  private String X = null;
  @SerializedName("Y")
  private String Y = null;
  @SerializedName("blockNumber")
  private String blockNumber = null;
  @SerializedName("entryNumber")
  private String entryNumber = null;
  @SerializedName("entryType")
  private String entryType = null;
  @SerializedName("germplasmDbId")
  private String germplasmDbId = null;
  @SerializedName("germplasmName")
  private String germplasmName = null;
  @SerializedName("observationUnitDbId")
  private String observationUnitDbId = null;
  @SerializedName("observationUnitName")
  private String observationUnitName = null;
  @SerializedName("observationUnitXref")
  private List<ObservationUnitXref> observationUnitXref = null;
  @SerializedName("observations")
  private List<ObservationSummary> observations = null;
  @SerializedName("pedigree")
  private String pedigree = null;
  @SerializedName("plantNumber")
  private String plantNumber = null;
  @SerializedName("plotNumber")
  private String plotNumber = null;
  @SerializedName("replicate")
  private String replicate = null;

  /**
   * The X position coordinate for an observation unit. Different systems may use different coordinate systems.
   **/
  @ApiModelProperty(value = "The X position coordinate for an observation unit. Different systems may use different coordinate systems.")
  public String getX() {
    return X;
  }
  public void setX(String X) {
    this.X = X;
  }

  /**
   * The Y position coordinate for an observation unit. Different systems may use different coordinate systems.
   **/
  @ApiModelProperty(value = "The Y position coordinate for an observation unit. Different systems may use different coordinate systems.")
  public String getY() {
    return Y;
  }
  public void setY(String Y) {
    this.Y = Y;
  }

  /**
   * The block number for an observation unit. Different systems may use different block designs.
   **/
  @ApiModelProperty(value = "The block number for an observation unit. Different systems may use different block designs.")
  public String getBlockNumber() {
    return blockNumber;
  }
  public void setBlockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
  }

  /**
   * The entry number for an observation unit. Different systems may use different entry systems.
   **/
  @ApiModelProperty(value = "The entry number for an observation unit. Different systems may use different entry systems.")
  public String getEntryNumber() {
    return entryNumber;
  }
  public void setEntryNumber(String entryNumber) {
    this.entryNumber = entryNumber;
  }

  /**
   * The type of entry for this observation unit. ex. \"check\", \"test\", \"filler\"
   **/
  @ApiModelProperty(value = "The type of entry for this observation unit. ex. \"check\", \"test\", \"filler\"")
  public String getEntryType() {
    return entryType;
  }
  public void setEntryType(String entryType) {
    this.entryType = entryType;
  }

  /**
   *  The ID which uniquely identifies a germplasm
   **/
  @ApiModelProperty(value = " The ID which uniquely identifies a germplasm")
  public String getGermplasmDbId() {
    return germplasmDbId;
  }
  public void setGermplasmDbId(String germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
  }

  /**
   * Name of the germplasm. It can be the prefered name and does not have to be unique.
   **/
  @ApiModelProperty(value = "Name of the germplasm. It can be the prefered name and does not have to be unique.")
  public String getGermplasmName() {
    return germplasmName;
  }
  public void setGermplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
  }

  /**
   * The ID which uniquely identifies an observation unit
   **/
  @ApiModelProperty(value = "The ID which uniquely identifies an observation unit")
  public String getObservationUnitDbId() {
    return observationUnitDbId;
  }
  public void setObservationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
  }

  /**
   * A human readable name for an observation unit
   **/
  @ApiModelProperty(value = "A human readable name for an observation unit")
  public String getObservationUnitName() {
    return observationUnitName;
  }
  public void setObservationUnitName(String observationUnitName) {
    this.observationUnitName = observationUnitName;
  }

  /**
   * A list of external references to this observation unit
   **/
  @ApiModelProperty(value = "A list of external references to this observation unit")
  public List<ObservationUnitXref> getObservationUnitXref() {
    return observationUnitXref;
  }
  public void setObservationUnitXref(List<ObservationUnitXref> observationUnitXref) {
    this.observationUnitXref = observationUnitXref;
  }

  /**
   * List of observations associated with this observation unit
   **/
  @ApiModelProperty(value = "List of observations associated with this observation unit")
  public List<ObservationSummary> getObservations() {
    return observations;
  }
  public void setObservations(List<ObservationSummary> observations) {
    this.observations = observations;
  }

  /**
   * The string representation of the pedigree of this observation unit
   **/
  @ApiModelProperty(value = "The string representation of the pedigree of this observation unit")
  public String getPedigree() {
    return pedigree;
  }
  public void setPedigree(String pedigree) {
    this.pedigree = pedigree;
  }

  /**
   * The plant number in a field. Applicable for observationLevel: \"plant\"
   **/
  @ApiModelProperty(value = "The plant number in a field. Applicable for observationLevel: \"plant\"")
  public String getPlantNumber() {
    return plantNumber;
  }
  public void setPlantNumber(String plantNumber) {
    this.plantNumber = plantNumber;
  }

  /**
   * The plot number in a field. Applicable for observationLevel: \"plot\"
   **/
  @ApiModelProperty(value = "The plot number in a field. Applicable for observationLevel: \"plot\"")
  public String getPlotNumber() {
    return plotNumber;
  }
  public void setPlotNumber(String plotNumber) {
    this.plotNumber = plotNumber;
  }

  /**
   * The replicate number of an observation unit. May be the same as blockNumber.
   **/
  @ApiModelProperty(value = "The replicate number of an observation unit. May be the same as blockNumber.")
  public String getReplicate() {
    return replicate;
  }
  public void setReplicate(String replicate) {
    this.replicate = replicate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObservationUnitStudy observationUnitStudy = (ObservationUnitStudy) o;
    return (this.X == null ? observationUnitStudy.X == null : this.X.equals(observationUnitStudy.X)) &&
        (this.Y == null ? observationUnitStudy.Y == null : this.Y.equals(observationUnitStudy.Y)) &&
        (this.blockNumber == null ? observationUnitStudy.blockNumber == null : this.blockNumber.equals(observationUnitStudy.blockNumber)) &&
        (this.entryNumber == null ? observationUnitStudy.entryNumber == null : this.entryNumber.equals(observationUnitStudy.entryNumber)) &&
        (this.entryType == null ? observationUnitStudy.entryType == null : this.entryType.equals(observationUnitStudy.entryType)) &&
        (this.germplasmDbId == null ? observationUnitStudy.germplasmDbId == null : this.germplasmDbId.equals(observationUnitStudy.germplasmDbId)) &&
        (this.germplasmName == null ? observationUnitStudy.germplasmName == null : this.germplasmName.equals(observationUnitStudy.germplasmName)) &&
        (this.observationUnitDbId == null ? observationUnitStudy.observationUnitDbId == null : this.observationUnitDbId.equals(observationUnitStudy.observationUnitDbId)) &&
        (this.observationUnitName == null ? observationUnitStudy.observationUnitName == null : this.observationUnitName.equals(observationUnitStudy.observationUnitName)) &&
        (this.observationUnitXref == null ? observationUnitStudy.observationUnitXref == null : this.observationUnitXref.equals(observationUnitStudy.observationUnitXref)) &&
        (this.observations == null ? observationUnitStudy.observations == null : this.observations.equals(observationUnitStudy.observations)) &&
        (this.pedigree == null ? observationUnitStudy.pedigree == null : this.pedigree.equals(observationUnitStudy.pedigree)) &&
        (this.plantNumber == null ? observationUnitStudy.plantNumber == null : this.plantNumber.equals(observationUnitStudy.plantNumber)) &&
        (this.plotNumber == null ? observationUnitStudy.plotNumber == null : this.plotNumber.equals(observationUnitStudy.plotNumber)) &&
        (this.replicate == null ? observationUnitStudy.replicate == null : this.replicate.equals(observationUnitStudy.replicate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.X == null ? 0: this.X.hashCode());
    result = 31 * result + (this.Y == null ? 0: this.Y.hashCode());
    result = 31 * result + (this.blockNumber == null ? 0: this.blockNumber.hashCode());
    result = 31 * result + (this.entryNumber == null ? 0: this.entryNumber.hashCode());
    result = 31 * result + (this.entryType == null ? 0: this.entryType.hashCode());
    result = 31 * result + (this.germplasmDbId == null ? 0: this.germplasmDbId.hashCode());
    result = 31 * result + (this.germplasmName == null ? 0: this.germplasmName.hashCode());
    result = 31 * result + (this.observationUnitDbId == null ? 0: this.observationUnitDbId.hashCode());
    result = 31 * result + (this.observationUnitName == null ? 0: this.observationUnitName.hashCode());
    result = 31 * result + (this.observationUnitXref == null ? 0: this.observationUnitXref.hashCode());
    result = 31 * result + (this.observations == null ? 0: this.observations.hashCode());
    result = 31 * result + (this.pedigree == null ? 0: this.pedigree.hashCode());
    result = 31 * result + (this.plantNumber == null ? 0: this.plantNumber.hashCode());
    result = 31 * result + (this.plotNumber == null ? 0: this.plotNumber.hashCode());
    result = 31 * result + (this.replicate == null ? 0: this.replicate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObservationUnitStudy {\n");
    
    sb.append("  X: ").append(X).append("\n");
    sb.append("  Y: ").append(Y).append("\n");
    sb.append("  blockNumber: ").append(blockNumber).append("\n");
    sb.append("  entryNumber: ").append(entryNumber).append("\n");
    sb.append("  entryType: ").append(entryType).append("\n");
    sb.append("  germplasmDbId: ").append(germplasmDbId).append("\n");
    sb.append("  germplasmName: ").append(germplasmName).append("\n");
    sb.append("  observationUnitDbId: ").append(observationUnitDbId).append("\n");
    sb.append("  observationUnitName: ").append(observationUnitName).append("\n");
    sb.append("  observationUnitXref: ").append(observationUnitXref).append("\n");
    sb.append("  observations: ").append(observations).append("\n");
    sb.append("  pedigree: ").append(pedigree).append("\n");
    sb.append("  plantNumber: ").append(plantNumber).append("\n");
    sb.append("  plotNumber: ").append(plotNumber).append("\n");
    sb.append("  replicate: ").append(replicate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
