/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class Season implements Serializable {
  
  @SerializedName("season")
  private String season = null;
  @SerializedName("seasonDbId")
  private String seasonDbId = null;
  @SerializedName("year")
  private String year = null;

  /**
   * Name of the season. ex. 'Spring', 'Q2', 'Season A', etc.
   **/
  @ApiModelProperty(value = "Name of the season. ex. 'Spring', 'Q2', 'Season A', etc.")
  public String getSeason() {
    return season;
  }
  public void setSeason(String season) {
    this.season = season;
  }

  /**
   * The ID which uniquely identifies a season
   **/
  @ApiModelProperty(value = "The ID which uniquely identifies a season")
  public String getSeasonDbId() {
    return seasonDbId;
  }
  public void setSeasonDbId(String seasonDbId) {
    this.seasonDbId = seasonDbId;
  }

  /**
   * The 4 digit year of the season.
   **/
  @ApiModelProperty(value = "The 4 digit year of the season.")
  public String getYear() {
    return year;
  }
  public void setYear(String year) {
    this.year = year;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Season season = (Season) o;
    return (this.season == null ? season.season == null : this.season.equals(season.season)) &&
        (this.seasonDbId == null ? season.seasonDbId == null : this.seasonDbId.equals(season.seasonDbId)) &&
        (this.year == null ? season.year == null : this.year.equals(season.year));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.season == null ? 0: this.season.hashCode());
    result = 31 * result + (this.seasonDbId == null ? 0: this.seasonDbId.hashCode());
    result = 31 * result + (this.year == null ? 0: this.year.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Season {\n");
    
    sb.append("  season: ").append(season).append("\n");
    sb.append("  seasonDbId: ").append(seasonDbId).append("\n");
    sb.append("  year: ").append(year).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
