/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class VendorSpecificationReferenceSystem implements Serializable {
  
  @SerializedName("URI")
  private String URI = null;
  @SerializedName("name")
  private String name = null;

  /**
   * The primary URI for this reference system
   **/
  @ApiModelProperty(value = "The primary URI for this reference system")
  public String getURI() {
    return URI;
  }
  public void setURI(String URI) {
    this.URI = URI;
  }

  /**
   * The human readable name for this reference system
   **/
  @ApiModelProperty(value = "The human readable name for this reference system")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorSpecificationReferenceSystem vendorSpecificationReferenceSystem = (VendorSpecificationReferenceSystem) o;
    return (this.URI == null ? vendorSpecificationReferenceSystem.URI == null : this.URI.equals(vendorSpecificationReferenceSystem.URI)) &&
        (this.name == null ? vendorSpecificationReferenceSystem.name == null : this.name.equals(vendorSpecificationReferenceSystem.name));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.URI == null ? 0: this.URI.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorSpecificationReferenceSystem {\n");
    
    sb.append("  URI: ").append(URI).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
