/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.TaxonID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class VendorPlateRequestSamples implements Serializable {
  
  @SerializedName("column")
  private String column = null;
  @SerializedName("concentration")
  private String concentration = null;
  @SerializedName("row")
  private String row = null;
  @SerializedName("sampleDbId")
  private String sampleDbId = null;
  @SerializedName("taxonId")
  private TaxonID taxonId = null;
  @SerializedName("tissueType")
  private String tissueType = null;
  @SerializedName("volume")
  private String volume = null;
  @SerializedName("well")
  private String well = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getColumn() {
    return column;
  }
  public void setColumn(String column) {
    this.column = column;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getConcentration() {
    return concentration;
  }
  public void setConcentration(String concentration) {
    this.concentration = concentration;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRow() {
    return row;
  }
  public void setRow(String row) {
    this.row = row;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSampleDbId() {
    return sampleDbId;
  }
  public void setSampleDbId(String sampleDbId) {
    this.sampleDbId = sampleDbId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TaxonID getTaxonId() {
    return taxonId;
  }
  public void setTaxonId(TaxonID taxonId) {
    this.taxonId = taxonId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTissueType() {
    return tissueType;
  }
  public void setTissueType(String tissueType) {
    this.tissueType = tissueType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVolume() {
    return volume;
  }
  public void setVolume(String volume) {
    this.volume = volume;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWell() {
    return well;
  }
  public void setWell(String well) {
    this.well = well;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorPlateRequestSamples vendorPlateRequestSamples = (VendorPlateRequestSamples) o;
    return (this.column == null ? vendorPlateRequestSamples.column == null : this.column.equals(vendorPlateRequestSamples.column)) &&
        (this.concentration == null ? vendorPlateRequestSamples.concentration == null : this.concentration.equals(vendorPlateRequestSamples.concentration)) &&
        (this.row == null ? vendorPlateRequestSamples.row == null : this.row.equals(vendorPlateRequestSamples.row)) &&
        (this.sampleDbId == null ? vendorPlateRequestSamples.sampleDbId == null : this.sampleDbId.equals(vendorPlateRequestSamples.sampleDbId)) &&
        (this.taxonId == null ? vendorPlateRequestSamples.taxonId == null : this.taxonId.equals(vendorPlateRequestSamples.taxonId)) &&
        (this.tissueType == null ? vendorPlateRequestSamples.tissueType == null : this.tissueType.equals(vendorPlateRequestSamples.tissueType)) &&
        (this.volume == null ? vendorPlateRequestSamples.volume == null : this.volume.equals(vendorPlateRequestSamples.volume)) &&
        (this.well == null ? vendorPlateRequestSamples.well == null : this.well.equals(vendorPlateRequestSamples.well));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.column == null ? 0: this.column.hashCode());
    result = 31 * result + (this.concentration == null ? 0: this.concentration.hashCode());
    result = 31 * result + (this.row == null ? 0: this.row.hashCode());
    result = 31 * result + (this.sampleDbId == null ? 0: this.sampleDbId.hashCode());
    result = 31 * result + (this.taxonId == null ? 0: this.taxonId.hashCode());
    result = 31 * result + (this.tissueType == null ? 0: this.tissueType.hashCode());
    result = 31 * result + (this.volume == null ? 0: this.volume.hashCode());
    result = 31 * result + (this.well == null ? 0: this.well.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorPlateRequestSamples {\n");
    
    sb.append("  column: ").append(column).append("\n");
    sb.append("  concentration: ").append(concentration).append("\n");
    sb.append("  row: ").append(row).append("\n");
    sb.append("  sampleDbId: ").append(sampleDbId).append("\n");
    sb.append("  taxonId: ").append(taxonId).append("\n");
    sb.append("  tissueType: ").append(tissueType).append("\n");
    sb.append("  volume: ").append(volume).append("\n");
    sb.append("  well: ").append(well).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
