/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.VendorSpecificationPlatformDeliverables;
import io.swagger.client.model.VendorSpecificationPlatformStatuses;
import io.swagger.client.model.VendorSpecificationReferenceSystem;
import io.swagger.client.model.VendorSpecificationStandardRequirement;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class VendorSpecificationPlatform implements Serializable {
  
  @SerializedName("contactEmail")
  private String contactEmail = null;
  @SerializedName("contactName")
  private String contactName = null;
  @SerializedName("contactPhone")
  private String contactPhone = null;
  @SerializedName("deliverables")
  private List<VendorSpecificationPlatformDeliverables> deliverables = null;
  @SerializedName("platformDescription")
  private String platformDescription = null;
  @SerializedName("platformName")
  private String platformName = null;
  @SerializedName("platformURL")
  private String platformURL = null;
  @SerializedName("shippingAddress")
  private String shippingAddress = null;
  @SerializedName("specificRequirements")
  private Object specificRequirements = null;
  @SerializedName("standardRequirements")
  private VendorSpecificationStandardRequirement standardRequirements = null;
  @SerializedName("statuses")
  private List<VendorSpecificationPlatformStatuses> statuses = null;
  @SerializedName("taxonomyIdSystem")
  private VendorSpecificationReferenceSystem taxonomyIdSystem = null;
  @SerializedName("tissueIdSystem")
  private VendorSpecificationReferenceSystem tissueIdSystem = null;

  /**
   * The primary email address to contact a particular vendor platform
   **/
  @ApiModelProperty(value = "The primary email address to contact a particular vendor platform")
  public String getContactEmail() {
    return contactEmail;
  }
  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  /**
   * The name or identifier of the primary vendor platfrom contact
   **/
  @ApiModelProperty(value = "The name or identifier of the primary vendor platfrom contact")
  public String getContactName() {
    return contactName;
  }
  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  /**
   * The phone number used to contact the vendor about a particular platform
   **/
  @ApiModelProperty(value = "The phone number used to contact the vendor about a particular platform")
  public String getContactPhone() {
    return contactPhone;
  }
  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  /**
   * List of specific deliverables provided by the vendor platform
   **/
  @ApiModelProperty(value = "List of specific deliverables provided by the vendor platform")
  public List<VendorSpecificationPlatformDeliverables> getDeliverables() {
    return deliverables;
  }
  public void setDeliverables(List<VendorSpecificationPlatformDeliverables> deliverables) {
    this.deliverables = deliverables;
  }

  /**
   * Description of the vendor platform
   **/
  @ApiModelProperty(value = "Description of the vendor platform")
  public String getPlatformDescription() {
    return platformDescription;
  }
  public void setPlatformDescription(String platformDescription) {
    this.platformDescription = platformDescription;
  }

  /**
   * The human readable name of a platform
   **/
  @ApiModelProperty(value = "The human readable name of a platform")
  public String getPlatformName() {
    return platformName;
  }
  public void setPlatformName(String platformName) {
    this.platformName = platformName;
  }

  /**
   * The URL for a vendor platform
   **/
  @ApiModelProperty(value = "The URL for a vendor platform")
  public String getPlatformURL() {
    return platformURL;
  }
  public void setPlatformURL(String platformURL) {
    this.platformURL = platformURL;
  }

  /**
   * The street address for a vendor platform
   **/
  @ApiModelProperty(value = "The street address for a vendor platform")
  public String getShippingAddress() {
    return shippingAddress;
  }
  public void setShippingAddress(String shippingAddress) {
    this.shippingAddress = shippingAddress;
  }

  /**
   * Additional arbitrary requirements for a particular platform
   **/
  @ApiModelProperty(value = "Additional arbitrary requirements for a particular platform")
  public Object getSpecificRequirements() {
    return specificRequirements;
  }
  public void setSpecificRequirements(Object specificRequirements) {
    this.specificRequirements = specificRequirements;
  }

  /**
   * Set of standard requirements for a vendor platform
   **/
  @ApiModelProperty(value = "Set of standard requirements for a vendor platform")
  public VendorSpecificationStandardRequirement getStandardRequirements() {
    return standardRequirements;
  }
  public void setStandardRequirements(VendorSpecificationStandardRequirement standardRequirements) {
    this.standardRequirements = standardRequirements;
  }

  /**
   * List of possible status messages for a vendor platform
   **/
  @ApiModelProperty(value = "List of possible status messages for a vendor platform")
  public List<VendorSpecificationPlatformStatuses> getStatuses() {
    return statuses;
  }
  public void setStatuses(List<VendorSpecificationPlatformStatuses> statuses) {
    this.statuses = statuses;
  }

  /**
   * Details about the systems used to track taxonomies
   **/
  @ApiModelProperty(value = "Details about the systems used to track taxonomies")
  public VendorSpecificationReferenceSystem getTaxonomyIdSystem() {
    return taxonomyIdSystem;
  }
  public void setTaxonomyIdSystem(VendorSpecificationReferenceSystem taxonomyIdSystem) {
    this.taxonomyIdSystem = taxonomyIdSystem;
  }

  /**
   * Details about the systems used to track sample IDs
   **/
  @ApiModelProperty(value = "Details about the systems used to track sample IDs")
  public VendorSpecificationReferenceSystem getTissueIdSystem() {
    return tissueIdSystem;
  }
  public void setTissueIdSystem(VendorSpecificationReferenceSystem tissueIdSystem) {
    this.tissueIdSystem = tissueIdSystem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorSpecificationPlatform vendorSpecificationPlatform = (VendorSpecificationPlatform) o;
    return (this.contactEmail == null ? vendorSpecificationPlatform.contactEmail == null : this.contactEmail.equals(vendorSpecificationPlatform.contactEmail)) &&
        (this.contactName == null ? vendorSpecificationPlatform.contactName == null : this.contactName.equals(vendorSpecificationPlatform.contactName)) &&
        (this.contactPhone == null ? vendorSpecificationPlatform.contactPhone == null : this.contactPhone.equals(vendorSpecificationPlatform.contactPhone)) &&
        (this.deliverables == null ? vendorSpecificationPlatform.deliverables == null : this.deliverables.equals(vendorSpecificationPlatform.deliverables)) &&
        (this.platformDescription == null ? vendorSpecificationPlatform.platformDescription == null : this.platformDescription.equals(vendorSpecificationPlatform.platformDescription)) &&
        (this.platformName == null ? vendorSpecificationPlatform.platformName == null : this.platformName.equals(vendorSpecificationPlatform.platformName)) &&
        (this.platformURL == null ? vendorSpecificationPlatform.platformURL == null : this.platformURL.equals(vendorSpecificationPlatform.platformURL)) &&
        (this.shippingAddress == null ? vendorSpecificationPlatform.shippingAddress == null : this.shippingAddress.equals(vendorSpecificationPlatform.shippingAddress)) &&
        (this.specificRequirements == null ? vendorSpecificationPlatform.specificRequirements == null : this.specificRequirements.equals(vendorSpecificationPlatform.specificRequirements)) &&
        (this.standardRequirements == null ? vendorSpecificationPlatform.standardRequirements == null : this.standardRequirements.equals(vendorSpecificationPlatform.standardRequirements)) &&
        (this.statuses == null ? vendorSpecificationPlatform.statuses == null : this.statuses.equals(vendorSpecificationPlatform.statuses)) &&
        (this.taxonomyIdSystem == null ? vendorSpecificationPlatform.taxonomyIdSystem == null : this.taxonomyIdSystem.equals(vendorSpecificationPlatform.taxonomyIdSystem)) &&
        (this.tissueIdSystem == null ? vendorSpecificationPlatform.tissueIdSystem == null : this.tissueIdSystem.equals(vendorSpecificationPlatform.tissueIdSystem));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.contactEmail == null ? 0: this.contactEmail.hashCode());
    result = 31 * result + (this.contactName == null ? 0: this.contactName.hashCode());
    result = 31 * result + (this.contactPhone == null ? 0: this.contactPhone.hashCode());
    result = 31 * result + (this.deliverables == null ? 0: this.deliverables.hashCode());
    result = 31 * result + (this.platformDescription == null ? 0: this.platformDescription.hashCode());
    result = 31 * result + (this.platformName == null ? 0: this.platformName.hashCode());
    result = 31 * result + (this.platformURL == null ? 0: this.platformURL.hashCode());
    result = 31 * result + (this.shippingAddress == null ? 0: this.shippingAddress.hashCode());
    result = 31 * result + (this.specificRequirements == null ? 0: this.specificRequirements.hashCode());
    result = 31 * result + (this.standardRequirements == null ? 0: this.standardRequirements.hashCode());
    result = 31 * result + (this.statuses == null ? 0: this.statuses.hashCode());
    result = 31 * result + (this.taxonomyIdSystem == null ? 0: this.taxonomyIdSystem.hashCode());
    result = 31 * result + (this.tissueIdSystem == null ? 0: this.tissueIdSystem.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorSpecificationPlatform {\n");
    
    sb.append("  contactEmail: ").append(contactEmail).append("\n");
    sb.append("  contactName: ").append(contactName).append("\n");
    sb.append("  contactPhone: ").append(contactPhone).append("\n");
    sb.append("  deliverables: ").append(deliverables).append("\n");
    sb.append("  platformDescription: ").append(platformDescription).append("\n");
    sb.append("  platformName: ").append(platformName).append("\n");
    sb.append("  platformURL: ").append(platformURL).append("\n");
    sb.append("  shippingAddress: ").append(shippingAddress).append("\n");
    sb.append("  specificRequirements: ").append(specificRequirements).append("\n");
    sb.append("  standardRequirements: ").append(standardRequirements).append("\n");
    sb.append("  statuses: ").append(statuses).append("\n");
    sb.append("  taxonomyIdSystem: ").append(taxonomyIdSystem).append("\n");
    sb.append("  tissueIdSystem: ").append(tissueIdSystem).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
