/**
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a> <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class VendorPlateFile implements Serializable {
  
  @SerializedName("URL")
  private String URL = null;
  @SerializedName("additionalInfo")
  private Map<String, String> additionalInfo = null;
  @SerializedName("fileType")
  private String fileType = null;
  @SerializedName("filename")
  private String filename = null;
  @SerializedName("md5sum")
  private String md5sum = null;
  @SerializedName("sampleDbIds")
  private List<String> sampleDbIds = null;

  /**
   * The URL to a file with the results of a vendor analysis
   **/
  @ApiModelProperty(required = true, value = "The URL to a file with the results of a vendor analysis")
  public String getURL() {
    return URL;
  }
  public void setURL(String URL) {
    this.URL = URL;
  }

  /**
   * Additional arbitrary info
   **/
  @ApiModelProperty(value = "Additional arbitrary info")
  public Map<String, String> getAdditionalInfo() {
    return additionalInfo;
  }
  public void setAdditionalInfo(Map<String, String> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  /**
   * Format of the file
   **/
  @ApiModelProperty(required = true, value = "Format of the file")
  public String getFileType() {
    return fileType;
  }
  public void setFileType(String fileType) {
    this.fileType = fileType;
  }

  /**
   * Name of the file
   **/
  @ApiModelProperty(required = true, value = "Name of the file")
  public String getFilename() {
    return filename;
  }
  public void setFilename(String filename) {
    this.filename = filename;
  }

  /**
   * MD5 Hash Check Sum for the file to confirm download without error
   **/
  @ApiModelProperty(value = "MD5 Hash Check Sum for the file to confirm download without error")
  public String getMd5sum() {
    return md5sum;
  }
  public void setMd5sum(String md5sum) {
    this.md5sum = md5sum;
  }

  /**
   * The list of sampleDbIds included in the file
   **/
  @ApiModelProperty(required = true, value = "The list of sampleDbIds included in the file")
  public List<String> getSampleDbIds() {
    return sampleDbIds;
  }
  public void setSampleDbIds(List<String> sampleDbIds) {
    this.sampleDbIds = sampleDbIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorPlateFile vendorPlateFile = (VendorPlateFile) o;
    return (this.URL == null ? vendorPlateFile.URL == null : this.URL.equals(vendorPlateFile.URL)) &&
        (this.additionalInfo == null ? vendorPlateFile.additionalInfo == null : this.additionalInfo.equals(vendorPlateFile.additionalInfo)) &&
        (this.fileType == null ? vendorPlateFile.fileType == null : this.fileType.equals(vendorPlateFile.fileType)) &&
        (this.filename == null ? vendorPlateFile.filename == null : this.filename.equals(vendorPlateFile.filename)) &&
        (this.md5sum == null ? vendorPlateFile.md5sum == null : this.md5sum.equals(vendorPlateFile.md5sum)) &&
        (this.sampleDbIds == null ? vendorPlateFile.sampleDbIds == null : this.sampleDbIds.equals(vendorPlateFile.sampleDbIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.URL == null ? 0: this.URL.hashCode());
    result = 31 * result + (this.additionalInfo == null ? 0: this.additionalInfo.hashCode());
    result = 31 * result + (this.fileType == null ? 0: this.fileType.hashCode());
    result = 31 * result + (this.filename == null ? 0: this.filename.hashCode());
    result = 31 * result + (this.md5sum == null ? 0: this.md5sum.hashCode());
    result = 31 * result + (this.sampleDbIds == null ? 0: this.sampleDbIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorPlateFile {\n");
    
    sb.append("  URL: ").append(URL).append("\n");
    sb.append("  additionalInfo: ").append(additionalInfo).append("\n");
    sb.append("  fileType: ").append(fileType).append("\n");
    sb.append("  filename: ").append(filename).append("\n");
    sb.append("  md5sum: ").append(md5sum).append("\n");
    sb.append("  sampleDbIds: ").append(sampleDbIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
