#
#    See the NOTICE file distributed with this work for additional information
#    regarding copyright ownership.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

name: Gradle Build Test Task

on:
  pull_request:
    type: [opened, edited]
  push:
    branches:
      - merge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew test
      - name: Publish Report Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: phenolib-test-results-${{ github.run_number }}
          path: ${{ github.workspace }}/app/build/reports/tests/*